// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :exec
INSERT INTO transactions (
        id,
        user_id,
        transaction_type,
        amount,
        created_at
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5
    )
`

type CreateTransactionParams struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          string             `json:"user_id"`
	TransactionType string             `json:"transaction_type"`
	Amount          int64              `json:"amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) error {
	_, err := q.db.Exec(ctx, createTransaction,
		arg.ID,
		arg.UserID,
		arg.TransactionType,
		arg.Amount,
		arg.CreatedAt,
	)
	return err
}

const listAllTransactions = `-- name: ListAllTransactions :many
SELECT id,
    user_id,
    transaction_type,
    amount,
    created_at
FROM transactions
WHERE -- 1. Handle Pagination: If cursor is Nil, ignore the ID filter.
    -- Otherwise, only show records older (smaller) than the cursor.
    (
        $1::uuid = '00000000-0000-0000-0000-000000000000'::uuid
        OR id < $1::uuid
    ) -- 2. Optional User ID filter
    AND (
        $2::varchar IS NULL
        OR user_id = $2::varchar
    ) -- 3. Optional Transaction Type filter
    AND (
        $3::varchar IS NULL
        OR transaction_type = $3::varchar
    )
ORDER BY id DESC
LIMIT $4
`

type ListAllTransactionsParams struct {
	CursorID        pgtype.UUID `json:"cursor_id"`
	UserID          pgtype.Text `json:"user_id"`
	TransactionType pgtype.Text `json:"transaction_type"`
	PageSize        int32       `json:"page_size"`
}

type ListAllTransactionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          string             `json:"user_id"`
	TransactionType string             `json:"transaction_type"`
	Amount          int64              `json:"amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// Fetches all transactions, newest first.
// Cursor: The last 'id' from the previous page (use uuid.Nil for the first page).
func (q *Queries) ListAllTransactions(ctx context.Context, arg ListAllTransactionsParams) ([]*ListAllTransactionsRow, error) {
	rows, err := q.db.Query(ctx, listAllTransactions,
		arg.CursorID,
		arg.UserID,
		arg.TransactionType,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListAllTransactionsRow{}
	for rows.Next() {
		var i ListAllTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TransactionType,
			&i.Amount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
