// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// List provides a mock function for the type MockRepository
func (_mock *MockRepository) List(ctx context.Context, userID *string, transactionType *TransactionType, pagination *Pagination) (*PageResult, error) {
	ret := _mock.Called(ctx, userID, transactionType, pagination)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *PageResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *TransactionType, *Pagination) (*PageResult, error)); ok {
		return returnFunc(ctx, userID, transactionType, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *string, *TransactionType, *Pagination) *PageResult); ok {
		r0 = returnFunc(ctx, userID, transactionType, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PageResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *string, *TransactionType, *Pagination) error); ok {
		r1 = returnFunc(ctx, userID, transactionType, pagination)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - userID *string
//   - transactionType *TransactionType
//   - pagination *Pagination
func (_e *MockRepository_Expecter) List(ctx interface{}, userID interface{}, transactionType interface{}, pagination interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, userID, transactionType, pagination)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, userID *string, transactionType *TransactionType, pagination *Pagination)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *TransactionType
		if args[2] != nil {
			arg2 = args[2].(*TransactionType)
		}
		var arg3 *Pagination
		if args[3] != nil {
			arg3 = args[3].(*Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(pageResult *PageResult, err error) *MockRepository_List_Call {
	_c.Call.Return(pageResult, err)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(ctx context.Context, userID *string, transactionType *TransactionType, pagination *Pagination) (*PageResult, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRepository
func (_mock *MockRepository) Save(ctx context.Context, t *Transaction) error {
	ret := _mock.Called(ctx, t)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Transaction) error); ok {
		r0 = returnFunc(ctx, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - t *Transaction
func (_e *MockRepository_Expecter) Save(ctx interface{}, t interface{}) *MockRepository_Save_Call {
	return &MockRepository_Save_Call{Call: _e.mock.On("Save", ctx, t)}
}

func (_c *MockRepository_Save_Call) Run(run func(ctx context.Context, t *Transaction)) *MockRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Transaction
		if args[1] != nil {
			arg1 = args[1].(*Transaction)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_Save_Call) Return(err error) *MockRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_Save_Call) RunAndReturn(run func(ctx context.Context, t *Transaction) error) *MockRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
