// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package kafka

import (
	"context"

	"github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageReader creates a new instance of MockMessageReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageReader {
	mock := &MockMessageReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageReader is an autogenerated mock type for the MessageReader type
type MockMessageReader struct {
	mock.Mock
}

type MockMessageReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageReader) EXPECT() *MockMessageReader_Expecter {
	return &MockMessageReader_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockMessageReader
func (_mock *MockMessageReader) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageReader_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMessageReader_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMessageReader_Expecter) Close() *MockMessageReader_Close_Call {
	return &MockMessageReader_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMessageReader_Close_Call) Run(run func()) *MockMessageReader_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageReader_Close_Call) Return(err error) *MockMessageReader_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageReader_Close_Call) RunAndReturn(run func() error) *MockMessageReader_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ReadMessage provides a mock function for the type MockMessageReader
func (_mock *MockMessageReader) ReadMessage(ctx context.Context) (kafka.Message, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ReadMessage")
	}

	var r0 kafka.Message
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (kafka.Message, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) kafka.Message); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(kafka.Message)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMessageReader_ReadMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadMessage'
type MockMessageReader_ReadMessage_Call struct {
	*mock.Call
}

// ReadMessage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMessageReader_Expecter) ReadMessage(ctx interface{}) *MockMessageReader_ReadMessage_Call {
	return &MockMessageReader_ReadMessage_Call{Call: _e.mock.On("ReadMessage", ctx)}
}

func (_c *MockMessageReader_ReadMessage_Call) Run(run func(ctx context.Context)) *MockMessageReader_ReadMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMessageReader_ReadMessage_Call) Return(message kafka.Message, err error) *MockMessageReader_ReadMessage_Call {
	_c.Call.Return(message, err)
	return _c
}

func (_c *MockMessageReader_ReadMessage_Call) RunAndReturn(run func(ctx context.Context) (kafka.Message, error)) *MockMessageReader_ReadMessage_Call {
	_c.Call.Return(run)
	return _c
}
